### ISSUE TITLE
Option to update dependency to next closest one, instead of latest

### ISSUE THREAD

**Issue by marco-carvalho** [depfu/depfu#51] opened 2020-12-17 18:34 UTC
Take a look at this PR:
https://github.com/marco-carvalho/modal/pull/72

Right now it is trying to update upgrade gatsby from "1.9.279" to "2.29.1". But this is such a big step, that I was wondering if could be possible to create a PR updating to "2.0.0", then to "2.0.1" and so on.

**Comment by theflow** [comment] 2022-07-20 09:28
Duplicate of #53

**Closed as not planned by theflow** 2022-07-20 09:28 UTC

**Comment by marco-carvalho** [comment] 2022-07-24 22:12
how this is duplicate of #53 if I created earlier?
